### ISSUE TITLE
Invitación a beta testers

### ISSUE THREAD

**Issue by srprogrammer** [kodiar/kodiar.github.io#1]
Estimados usuarios del addon Kodi de subtítulos Subdivx:

Les pedimos ayuda probando lo que esperamos sea la evolución del addon.

Hemos creado esta organización "kodiar" en GitHub y vamos a adoptar el addon que hasta ahora mantenía @ramiro en solitario quien está al tanto y es parte de la organización. La idea es ayudarlo.

Por favor seguir las instrucciones en el archivo https://github.com/kodiar/kodiar.github.io/blob/main/README.md
para instalar nuestro repositorio externo de versiones beta, instalar la versión 0.4.1 y probar su funcionamiento a fondo dentro de sus posibilidades.

¡Gracias!

@gboado
@pyro12
@TheArgentinian
@methodmann

**Comment by pyro12** [comment]
Gracia por continuar el trabajo en este proyecto!

El addon parece a funcionar muy bien.  El unico problema ha encontrado es que algunos de los archivos parecen contener el html del sitio web subdivx.com en lugar de los subtitulos.  Creo que esto es un problema con los archivos mismos porque obtengo el mismo resultado si descargo los subtítulos manualmente de subdivx.com, los descomprimo y los abro en un editor de texto.  https://www.subdivx.com/descargar.php?id=44723 es un buen ejemplo. No veo ningun errors en el log:

https://pastebin.com/iU4DGP8D

**Comment by methodmann** [comment]
Buenas tardes, muchas gracias por hacer un esfuerzo y continuar con este trabajo.Gracias tambien por incluirme como tester en el proyecto.Acabo de instalar el addon para probarlo en una nvidia shield con sistema android y kodi 19.3 matrix e instala perfectamente y me realiza la busqueda y encuentra subtitulo pero no lo descarga.Al pulsar el subtitulo me da error de registro.No se si sera la version.En cuanto pueda miro como descargar un log y lo añado.Grcias

**Comment by methodmann** [comment]
Dejo aqui un extracto del log de kodi.Gracias

[kodi.log](https://github.com/kodiar/kodiar.github.io/files/14484964/kodi.log)

**Comment by srprogrammer** [comment]
El sitio no está funcionando bien. En al menos algunos resultados de búsquedas (por ejemplo la que se ve en los logs de @pyro12) no es posible hacer click en los resultados para pasar a descargar el mismo.

Esto afecta al uso normal de subdivx.com como usuario anónimo y como usuario registrado y logueado al sitio.

De todos modos el addon no maneja bien estas situaciones de error ya que si descarga algo descarga un HTML inservible.

**Comment by fernandolr0** [comment]
Buenas! Primero gracias por el gran aporte para toda la comunidad de habla hispana!! No soy programador ni tengo demasiada experiencia en KODI, solo comparto una parte de mi experiencia por un error que tenia. por si a alguien (y a los desarrolladores) le sirve, creo que se soluciona simplemente agregando una dependencia.
Las lineas del log que me llamaron la atencion fueron: 

2024-05-29 19:25:47.094 T:6400     info <general>: SUBDIVX - save_subtitles: Decompressing C:\Users\Fer\AppData\Roaming\Kodi\userdata\addon_data\service.subtitles.subdivx\tmp71m8rrmi\subdivx.zip
2024-05-29 19:25:47.094 T:6400  warning <general>: XFILE::CDirectoryFactory::Create - unsupported protocol(archive) in archive://C%3A%5CUsers%5CFer%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cservice.subtitles.subdivx%5Ctmp71m8rrmi%5Csubdivx.zip/
2024-05-29 19:25:47.094 T:6400     info <general>: SUBDIVX - handle_compressed_subs: Failed to unpack subtitles

La solución fue instalar desde el repositorio de Kodi > Sistemas de archivos virtuales > Archive support.

Gracias nuevamente! Saludos.

**Comment by ramiro** [comment]
Hola @fernandolr0 No recuerdo bien los detalles técnicos pero esa dependencia no se puede expresar mediante el mecanismo que ofrece Kodi con el archivo `addon.xml`.

Debería revisar si eso ha cambiado recientemente.

**Comment by ramiro** [comment]
[Aquí](https://github.com/ramiro/service.subtitles.subdivx/issues/39#issuecomment-464533035) encontré la explicación de feb 2019:

> `vfs.libarchive`, por razones de seguridad, es un add-on que no puede instalarse en forma automática (como usualmente sucede) al instalar un add-on como el nuestro aun cuando este tiene declarada una dependencia de aquél (dependencia que para otros tipos de add-ons es la responsable de disparar su instalación automática por parte de Kodi). Es el usuario el que tiene que estar pre-avisado y debe instalarlo manual y explícitamente.

**Comment by TheArgentinian** [comment]
Me sale error cuando intento descargar cualquier subtítulo. Tengo Archive Support y RAR a.s. instalado. Esto dice el log:

> 2024-06-04 19:20:50.486 T:6818     info <general>: SUBDIVX - Version: 0.4.1 -- Action: download
> 
> 2024-06-04 19:20:50.488 T:6818    error <general>: GetDirectory - Error getting /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/
> 
> 2024-06-04 19:20:50.489 T:6818     info <general>: SUBDIVX - cleanup_tempdirs: Results: 0 of 1 dirs removed
> 
> 2024-06-04 19:20:50.507 T:6818    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'FileNotFoundError'>
>                                                    Error Contents: [Errno 2] No such file or directory: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpof5mbzjb'
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.subdivx/service.py", line 34, in <module>
>                                                        main()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.subdivx/service.py", line 30, in main
>                                                        action_download()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.subdivx/libs/main.py", line 188, in action_download
>                                                        workdir = tempfile.mkdtemp(dir=profile_dir)
>                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/tempfile.py", line 368, in mkdtemp
>                                                        _os.mkdir(file, 0o700)
>                                                    FileNotFoundError: [Errno 2] No such file or directory: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpof5mbzjb'
>                                                    -->End of Python script error report<--

**Comment by pyro12** [comment]
@TheArgentinian 

Desafortunadamente, nunca mire el log, pero el app no funciono hasta que abrí el dialogo de 'settings' y hice clic en "Aceptar". Desde entonces ha funcionado muy bien.

Se que suena extrano, pero tal vez al hacer clic en "Aceptar" se crea un directorio que debe existir y debería haberse creado durante la instalacion. Facil de probar.

**Comment by TheArgentinian** [comment]
> @TheArgentinian
> 
> Desafortunadamente, nunca mire el log, pero el app no funciono hasta que abrí el dialogo de 'settings' y hice clic en "Aceptar". Desde entonces ha funcionado muy bien.
> 
> Se que suena extrano, pero tal vez al hacer clic en "Aceptar" se crea un directorio que debe existir y debería haberse creado durante la instalacion. Facil de probar.

Lo solucionó. Gracias!

**Comment by pyro12** [comment]
@TheArgentinian 

Abri un issue sobre el problema.  Como dije, no tenia un log.  Publique su log alli, por favor

https://github.com/kodiar/kodiar.github.io/issues/2

**Comment by pyro12** [comment]
Saludos,

Hace aproximadamente una semana que esta app no me funciona.  Alguien mas esta teniendo problemas?

**Comment by TheArgentinian** [comment]
> Saludos,
> 
> Hace aproximadamente una semana que esta app no me funciona. Alguien mas esta teniendo problemas?

confirmo que no muestra ningún resultado.

Ahora uso el addon de Opensubtitles.com. Me pudrió renegar con esta mierda.

**Comment by methodmann** [comment]
A mi tampoco me muestra resultados. Al menos ayer 😢 Saludos

**Comment by pyro12** [comment]
He notado que  subdivx.com no usa https jamas.  Intente cambiar la linea 86 in subdivx_api.py to 

  `  req.add_header("Referer", "http://www.subdivx.com")
`

pero todavia no funciona.  

Hay otras lineas que necesito cambiar?

**Comment by OtroYorch** [comment]
lo acabo de descargar, reporto que no arroja ningun resultado, y la pelicula en cuestion si tiene subtitulos en subdivx

**Comment by pyro12** [comment]
Alguien ha tenido tiempo de ver esto?

**Comment by TheArgentinian** [comment]
Está funcionando de nuevo el addon. Habrá cambiado algo detrás de escenas.

**Comment by ramiro** [comment]
Pude probar algo el finde pero por ahora no tengo tiempo de trabajar sobre el tema.

Lo dejo aquí por si vuelve a pasar (y ojo que puede que vuelva a romperse):

La estrategia que estamos usando en el addon todavía es correcta. O sea que el sitio no ha cambiado nada importante estructuralmente.

Pero en el momento de enviar la búsqueda responde:
```json
{
  "sEcho":"0",
  "iTotalRecords":0,
  "iTotalDisplayRecords":0,
  "aaData":[],
  "mensaje":"Por favor espera antes de realizar otra busqueda."
}
```

Revisando los headers veo que en los responses hay una cookie `sdx` que el server quiere setear:

```
Set-Cookie: sdx=89u168ha0ne8ge6ceh2qo11d1u; path=/
```

Si la envío en la request de búsqueda el sitio vuelve a permitirle al addon que haga búsquedas.

Creo que esto significa dejar de usar la urllib de la stdlib de Python en modo básico donde cada request es su propio mundo y comenzar a usar algo que nos permita mantener sesiones anónimas mediante cookies que se almacenan en disco enlazando todos los requests, mas parecido a un browser.
Hay que almacenar las cookies en disco porque por la arquitectura de addons de Kodi cada invocación del addon es un proceso del intérprete Python distinto: Un proceso cuando busca y otro totalmente distinto cuando descarga.

Usar la biblioteca de cookies de la stdlib e integrarla con urllib es innecesariamente complejo porque hay que hacerlo a bajo nivel. 

Busqué bibliotecas de 3ros. que esté disponibles como addon oficial en los repos de Kodi que permitan hacer eso desde un  nivel mas alto y no encontré otra que `requests` que en principio quería evitar como dependencia pero parece que no va a haber alternativa.

**Comment by methodmann** [comment]
Me quito el sombrero con ustedes señores. Muchas gracias por todo su
trabajo

**Comment by srprogrammer** [comment]
Estimados,

Se implementó un fix para esto en la versión 0.4.2 y algunas otras mejoras en 0.4.3.

Por favor probar y reportar errores. PERO no aquí. He activado el reporte de errores en el repositorio https://github.com/kodiar/service.subtitles.subdivx/issues así que hagamoslo allí.

**Comment by ramiro** [comment]
@ajrojasa @Tribujos por favor leer este thread

**Comment by ajrojasa** [comment]
Hola a todos

@ramiro me invito ayer a este grupo porque estuve jugando con el codigo para ver si podia ver que estaba haciendo que el addon no funcionara (en que estaba en el repo de ramiro) y termine haciendo un mini ambiente de test para probarlo en mi maquina, finalmente pude rescatar la lista de busqueda desde subdivx, de todas maneras les dejo las fuentes de lo que estuve haciendo ayer, voy a probar en kodi lo que esta en este repo.

Saludos a todos.
[subdivx_addon_test.zip](https://github.com/user-attachments/files/16444122/subdivx_addon_test.zip)

**Comment by ramiro** [comment]
Estimados,

¿Tienen feedback sobre la versión 0.4.3? ¿Funciona? ¿Nunca? ¿Pocas veces? ¿Siempre?

La idea es ver si podemos graduar la misma para publicarla en el repositorio oficial de addons Kodi.

¡Gracias!

**Comment by gboado** [comment]
Hola,
A mi me funciona bien. Las veces que no anduvo es porque el sitio tenía algún problema, pero más allá de eso no tengo ningún comentario.
Saludos
________________________________

**Comment by ajrojasa** [comment]
A mi hasta el momento me ha funcionado perfecto

**Comment by TheArgentinian** [comment]
Funcionar, funciona, pero no notan un delay cuando está buscando un subtitulo?

**Comment by OtroYorch** [comment]
Pense que era mi red, pero sí, esta lento

**Comment by srprogrammer** [comment]
@TheArgentinian @OtroYorch ¿Podrían probar haciendo una búsqueda con los mismos términos usando el browser,  comparando los tiempos y contar aquí qué conclusiones sacan?

Puede que haya una diferencia de tiempos  cuando se buscan subtítulos de una película. Ejemplo: Sintel del año 2010.
Si no hay resultados para ese año busca nuevamente con Sintel 2009 y si eso tampoco trae resultados busca Sintel 2011.
Este es un cambio que se implementó en la última versión.

**Comment by gboado** [comment]
En general subdivx está medio lento. No creo que globalmente el addin sea mucho más lento

Sent from my iPhone

On Aug 15, 2024, at 16:35, Federico ***@***.***> wrote:

﻿

Funcionar, funciona, pero no notan un delay cuando está buscando un subtitulo?

**Comment by TheArgentinian** [comment]
El buscador de la página web no es tan rápido pero el addon tiene unos segundos extras. Probe con títulos populares y con menos resultados.

**Comment by srprogrammer** [comment]
> El buscador de la página web no es tan rápido pero el addon tiene unos segundos extras. Probe con títulos populares y con menos resultados.

¿Por que no pones un par de ejemplos concretos con los tiempos?

Algo más cuantitativo. Más útil.

**Comment by TheArgentinian** [comment]
> > El buscador de la página web no es tan rápido pero el addon tiene unos segundos extras. Probe con títulos populares y con menos resultados.
> 
> ¿Por que no pones un par de ejemplos concretos con los tiempos?
> 
> Algo más cuantitativo. Más útil.

Perdon, no me puse a cronometrar los resultados. ¿Qué diferencia hace  5 o 10 seg más? Hay delay y punto. 

Si es lo que hay, es lo que hay. Peor es que no ande.

**Comment by octabenavidez** [comment]
Buenas banco mucho la iniciativa de poder combinar kodi con subdivx y los felicito muchachos, de igual manera les consulto ahora mismo se encuentra funcionando? Porque yo intento buscar títulos y no me da ningún resultado

**Comment by TheArgentinian** [comment]
> Buenas banco mucho la iniciativa de poder combinar kodi con subdivx y los felicito muchachos, de igual manera les consulto ahora mismo se encuentra funcionando? Porque yo intento buscar títulos y no me da ningún resultado

Se rompió de nuevo. Me aparece que no encontró ningún resultado.

**Comment by octabenavidez** [comment]
> > Buenas banco mucho la iniciativa de poder combinar kodi con subdivx y los felicito muchachos, de igual manera les consulto ahora mismo se encuentra funcionando? Porque yo intento buscar títulos y no me da ningún resultado
> 
> Se rompió de nuevo. Me aparece que no encontró ningún resultado.

Que lastima ojalá pueda arreglarse rápido porque es demasiado buena fuente de subs

**Comment by gboado** [comment]
Si. Yo tuve el mismo problema. Previamente tiraba un error, quizás por timeout. Ahora termina correctamente pero sin resultados, y a una velocidad sospechosamente alta.
Sent from my iPhone

On Sep 25, 2024, at 13:41, octabenavidez ***@***.***> wrote:

﻿

Buenas banco mucho la iniciativa de poder combinar kodi con subdivx y los felicito muchachos, de igual manera les consulto ahora mismo se encuentra funcionando? Porque yo intento buscar títulos y no me da ningún resultado

Se rompió de nuevo. Me aparece que no encontró ningún resultado.

Que lastima ojalá pueda arreglarse rápido porque es demasiado buena fuente de subs

**Comment by methodmann** [comment]
Efectivamente lleva unos días si arrojar resultados :(

**Comment by octabenavidez** [comment]
Ojala se pueda solucionar rápido es la mejor extensión de subtítulos sin duda, deberían promocionar el proyecto en alguna comunidad de Reddit y aceptar donaciones para motivar mas al desarrollo

**Comment by ramiro** [comment]
https://github.com/kodiar/service.subtitles.subdivx/issues/1#issuecomment-2409895629
